In [2]:
import numpy as np
import pandas as pd
import nltk
#download vader from nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
#creating an object of sentiment intensity analyzer
sia= SentimentIntensityAnalyzer()
#uploading csv file
#from google.colab import files
#uploaded = files.upload()
#reading csv file
df = pd.read_csv('reviews.csv')
df.head()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/benjoomeverywhere/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

,asin,name,rating,date,verified,title,body,helpfulVotes
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0

In [3]:
text= "Bobby is an amazing guy"
sia.polarity_scores(text)

{'neg': 0.0, 'neu': 0.513, 'pos': 0.487, 'compound': 0.5859}

In [4]:
text= "The food delivered was really very bad"
sia.polarity_scores(text)

{'neg': 0.404, 'neu': 0.596, 'pos': 0.0, 'compound': -0.6214}

In [5]:
#creating new column scores using polarity scores function
df['scores']=df['body'].apply(lambda body: sia.polarity_scores(str(body)))
df.head()

,asin,name,rating,date,verified,title,body,helpfulVotes,scores
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0,"{'neg': 0.08, 'neu': 0.816, 'pos': 0.105, 'com..."
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0,"{'neg': 0.02, 'neu': 0.876, 'pos': 0.104, 'com..."
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0,"{'neg': 0.051, 'neu': 0.846, 'pos': 0.103, 'co..."
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0,"{'neg': 0.0, 'neu': 0.844, 'pos': 0.156, 'comp..."
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0,"{'neg': 0.066, 'neu': 0.814, 'pos': 0.121, 'co..."

In [6]:
df['compound']=df['scores'].apply(lambda score_dict:score_dict['compound'])
df.head()
df['pos']=df['scores'].apply(lambda pos_dict:pos_dict['pos'])
df.head()
df['neg']=df['scores'].apply(lambda neg_dict:neg_dict['neg'])
df.head()

,asin,name,rating,date,verified,title,body,helpfulVotes,scores,compound,pos,neg
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0,"{'neg': 0.08, 'neu': 0.816, 'pos': 0.105, 'com...",0.8629,0.105,0.080
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0,"{'neg': 0.02, 'neu': 0.876, 'pos': 0.104, 'com...",0.8860,0.104,0.020
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0,"{'neg': 0.051, 'neu': 0.846, 'pos': 0.103, 'co...",0.7992,0.103,0.051
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0,"{'neg': 0.0, 'neu': 0.844, 'pos': 0.156, 'comp...",0.9592,0.156,0.000
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0,"{'neg': 0.066, 'neu': 0.814, 'pos': 0.121, 'co...",0.7745,0.121,0.066

In [7]:
df['type']=''
df.loc[df.compound>0,'type']='POS'
df.loc[df.compound==0,'type']='NEUTRAL'
df.loc[df.compound<0,'type']='NEG'
df.head()

,asin,name,rating,date,verified,title,body,helpfulVotes,scores,compound,pos,neg,type
0,B0000SX2UC,Janet,3,"October 11, 2005",False,"Def not best, but not worst",I had the Samsung A600 for awhile which is abs...,1.0,"{'neg': 0.08, 'neu': 0.816, 'pos': 0.105, 'com...",0.8629,0.105,0.080,POS
1,B0000SX2UC,Luke Wyatt,1,"January 7, 2004",False,Text Messaging Doesn't Work,Due to a software issue between Nokia and Spri...,17.0,"{'neg': 0.02, 'neu': 0.876, 'pos': 0.104, 'com...",0.8860,0.104,0.020,POS
2,B0000SX2UC,Brooke,5,"December 30, 2003",False,Love This Phone,"This is a great, reliable phone. I also purcha...",5.0,"{'neg': 0.051, 'neu': 0.846, 'pos': 0.103, 'co...",0.7992,0.103,0.051,POS
3,B0000SX2UC,amy m. teague,3,"March 18, 2004",False,"Love the Phone, BUT...!","I love the phone and all, because I really did...",1.0,"{'neg': 0.0, 'neu': 0.844, 'pos': 0.156, 'comp...",0.9592,0.156,0.000,POS
4,B0000SX2UC,tristazbimmer,4,"August 28, 2005",False,"Great phone service and options, lousy case!",The phone has been great for every purpose it ...,1.0,"{'neg': 0.066, 'neu': 0.814, 'pos': 0.121, 'co...",0.7745,0.121,0.066,POS

In [9]:
len=df.shape
(rows,cols)=len
pos=0
neg=0
neutral=0
for i in range(0,rows):
    if df.loc[i][12]=="POS":
        pos=pos+1
    if df.loc[i][12]=="NEG":
        neg=neg+1
    if df.loc[i][12]=="NEUTRAL":
        neutral=neutral+1
print("Positive :"+str(pos) + "  Negative :" + str(neg) + "   Neutral :"+ str(neutral))

Positive :46034  Negative :13698   Neutral :8254